---
# tasks file for roles/network

- name: Template the network config
  template:
    src: ens192.j2
    dest: /etc/network/interfaces.d/ens192
    owner: root
    group: root
    mode: 0644
     
- name: Disable dhcpcd
  service:
    name: dhcpcd
    state: stopped
    enabled: false

- name: Remove dhcpcd
  apt:
    name: dhcpcd5
    state: absent

- name: Set the hostname for boot
  template:
    src: hostname.j2
    dest: /etc/hostname

- name: Set hostname
  command: "hostname {{ hostname }}"
  when:
    - (ansible_fqdn != hostname)
