---
# tasks file for roles/docker
- name: Install docker
  apt:
    name: docker-ce
    state: latest
  async: 600
  poll: 10

- name: Ensure rsync is installed
  apt:
    name: rsync
    state: present

- name: Copy the workshop scripts up
  synchronize:
    src: ../workshop-scripts/
    dest: /opt/workshop-scripts/
    use_ssh_args: yes

- name: Pull the workshop git repos
  git:
    dest: "/opt/{{ item }}"
    repo: "https://github.com/TimJDFletcher/{{ item }}"
  with_items:
    - docker-workshop
    - docker-scripts
