---
# tasks file for roles/update
- name: update packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  async: 600
  poll: 10

- name: Clean apt caches
  command: apt-get clean
  changed_when: false

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Rebooting machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required_file.stat.exists

- name: Waiting for the machine to come back
  local_action: wait_for host={{ ansible_host }} state=started port=22 delay=30
  become: no
  when: reboot_required_file.stat.exists
