---
# tasks file for roles/update

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: update packages
  apt:
    upgrade: dist
    async: 600
    poll: 10
